Algoritmo "Laço de Repetição FOR"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Felipe Evangelista dos Santos
// Descrição   : Mostrar uma lista de números de 1 a 500
// Autor(a)    : César Augusto Pereira
// Data atual  : 22/10/2021
Var
// Seção de Declarações das variáveis
   i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para i de 1 ate 500 passo 1 faca
     escreval(i)
fimpara

Fimalgoritmo