Algoritmo "Números de 1 até 1000"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Felipe Evangelista dos Santos 
// Descrição   : Apresentação de uma lista de números de 1 até 1000
// Autor(a)    : César Augusto Pereira
// Data atual  : 20/10/2021
Var
// Seção de Declarações das variáveis 
    i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para i de 1 ate 1000 passo 1 faca
        escreval(i)
   fimpara

Fimalgoritmo